-- 1. Tạo cơ sở dữ liệu và cài đặt bảng
-- Tạo Database
CREATE DATABASE Transerco_Bus_Management_DB
-- Tạo bảng PHUONGTIEN
GO
CREATE TABLE PHUONGTIEN(
    Ma_Phuong_Tien NVARCHAR(10),
    Ma_Tuyen NVARCHAR(10),
    Ma_Tai_Xe NVARCHAR(10),
    Ten_Phuong_Tien NVARCHAR(50),
    Bien_Kiem_Soat NVARCHAR(12),
    Hang_San_Xuat NVARCHAR (50),
    Nam_San_Xuat INT,
    So_Khung VARCHAR(17), -- Tiêu chuẩn quốc tế VIN gồm 17 kí tự
    So_Cho_Ngoi INT
);
-- Tạo bảng TAIXE_LIENHE
GO
CREATE TABLE TAIXE_LIENHE(
    Ma_Tai_Xe NVARCHAR(10),
    Loai_Lien_He_Email_SDT NVARCHAR(20),
    Gia_Tri NVARCHAR(100)
);
-- Tạo bảng TUYENXE
GO
CREATE TABLE TUYENXE(
    Ma_Tuyen NVARCHAR(10),
    Ma_Chi_Nhanh NVARCHAR(10),
    Ten_Tuyen NVARCHAR(5),
    Gio_Bat_Dau TIME,
    Gio_Ket_Thuc TIME
);
-- Tạo bảng TAIXE
GO
CREATE TABLE TAIXE(
    Ma_Tai_Xe NVARCHAR(10),
    Ma_Phuong_Tien NVARCHAR(10),
    Ma_Chi_Nhanh NVARCHAR(10),
    Ho_Va_Ten NVARCHAR(100),
    Ngay_Sinh DATE,
    Dia_Chi NVARCHAR(200)
);
-- Tạo bảng TRAMKHOIDAU
GO
CREATE TABLE TRAMKHOIDAU(
    Ma_Tuyen NVARCHAR(10),
    Ma_Tram NVARCHAR(10)
);
-- Tạo bảng TRAMKETTHUC
GO
CREATE TABLE TRAMKETTHUC(
    Ma_Tuyen NVARCHAR(10),
    Ma_Tram NVARCHAR(10)
);
-- Tạo bảng LOTRINH
GO
CREATE TABLE LOTRINH(
    Ma_Tuyen NVARCHAR(10),
    Ma_Tram NVARCHAR(10),
    Thu_Tu_Tram INT
);
-- Tạo bảng TP_TUYENXE
GO
CREATE TABLE TP_TUYENXE(
    Ma_Thanh_Pho NVARCHAR(10),
    Ma_Tuyen NVARCHAR(10)
);
-- Tạo bảng CN_TUYENXE
GO
CREATE TABLE CN_TUYENXE(
    Ma_Chi_Nhanh NVARCHAR(10),
    Ma_Tuyen NVARCHAR(10)
);
-- Tạo bảng THANHPHO
GO
CREATE TABLE THANHPHO(
    Ma_Thanh_Pho NVARCHAR(10),
    Ten_Thanh_Pho NVARCHAR(100)
);
-- Tạo bảng TRAMXE
GO
CREATE TABLE TRAMXE(
    Ma_Tram NVARCHAR(10),
    Vi_Tri_Tram NVARCHAR(200)
);
-- Tạo bảng CHINHANH_LIENHE
GO
CREATE TABLE CHINHANH_LIENHE(
    Ma_Chi_Nhanh NVARCHAR(10),
    Loai_Lien_He_Email_SDT NVARCHAR(20),
    Gia_Tri NVARCHAR(100)
);
-- Tạo bảng CHINHANH
GO
CREATE TABLE CHINHANH(
    Ma_Chi_Nhanh NVARCHAR(10),
    Ma_Thanh_Pho NVARCHAR(10),
    Ten_Chi_Nhanh NVARCHAR(100),
    Dia_Chi NVARCHAR(200)
);

-- 2. Cài đặt PK và FK
-- Ràng buộc không nhận giá trị NULL
-- tbl.PHUONGTIEN
ALTER TABLE PHUONGTIEN ALTER COLUMN Ma_Phuong_Tien NVARCHAR(10) NOT NULL;
ALTER TABLE PHUONGTIEN ALTER COLUMN Bien_Kiem_Soat NVARCHAR(12) NOT NULL;
ALTER TABLE PHUONGTIEN ALTER COLUMN So_Khung VARCHAR(17) NOT NULL;

-- tbl.TRAMKETTHUC
ALTER TABLE TRAMKETTHUC ALTER COLUMN Ma_Tuyen NVARCHAR(10) NOT NULL;
ALTER TABLE TRAMKETTHUC ALTER COLUMN Ma_Tram NVARCHAR(10) NOT NULL;

-- tbl.TUYENXE
ALTER TABLE TUYENXE ALTER COLUMN Ma_Tuyen NVARCHAR(10) NOT NULL;
ALTER TABLE TUYENXE ALTER COLUMN Ma_Chi_Nhanh NVARCHAR(10) NOT NULL;
ALTER TABLE TUYENXE ALTER COLUMN Ten_Tuyen NVARCHAR(5) NOT NULL;

-- tbl.TAIXE
ALTER TABLE TAIXE ALTER COLUMN Ma_Tai_Xe NVARCHAR(10) NOT NULL;
ALTER TABLE TAIXE ALTER COLUMN Ma_Chi_Nhanh NVARCHAR(10) NOT NULL;

-- tbl.TRAMKHOIDAU
ALTER TABLE TRAMKHOIDAU ALTER COLUMN Ma_Tuyen NVARCHAR(10) NOT NULL;
ALTER TABLE TRAMKHOIDAU ALTER COLUMN Ma_Tram NVARCHAR(10) NOT NULL;

-- tbl.LOTRINH
ALTER TABLE LOTRINH ALTER COLUMN Ma_Tuyen NVARCHAR(10) NOT NULL;
ALTER TABLE LOTRINH ALTER COLUMN Ma_Tram NVARCHAR(10) NOT NULL;

-- tbl.TP_TUYENXE
ALTER TABLE TP_TUYENXE ALTER COLUMN Ma_Thanh_Pho NVARCHAR(10) NOT NULL;
ALTER TABLE TP_TUYENXE ALTER COLUMN Ma_Tuyen NVARCHAR(10) NOT NULL;

-- tbl.CN_TUYENXE
ALTER TABLE CN_TUYENXE ALTER COLUMN Ma_Chi_Nhanh NVARCHAR(10) NOT NULL;
ALTER TABLE CN_TUYENXE ALTER COLUMN Ma_Tuyen NVARCHAR(10) NOT NULL;

-- tbl.THANHPHO
ALTER TABLE THANHPHO ALTER COLUMN Ma_Thanh_Pho NVARCHAR(10) NOT NULL;
ALTER TABLE THANHPHO ALTER COLUMN Ten_Thanh_Pho NVARCHAR(100) NOT NULL;

-- tbl.TAIXE_LIENHE
ALTER TABLE TAIXE_LIENHE ALTER COLUMN Ma_Tai_Xe NVARCHAR(10) NOT NULL;
ALTER TABLE TAIXE_LIENHE ALTER COLUMN Loai_Lien_He_Email_SDT NVARCHAR(10) NOT NULL;
ALTER TABLE TAIXE_LIENHE ALTER COLUMN Gia_Tri NVARCHAR(10) NOT NULL;

-- tbl.TRAMXE
ALTER TABLE TRAMXE ALTER COLUMN Ma_Tram NVARCHAR(10) NOT NULL;
ALTER TABLE TRAMXE ALTER COLUMN Vi_Tri_Tram NVARCHAR(10) NOT NULL;

-- tbl.CHINHANH_LIENHE
ALTER TABLE CHINHANH_LIENHE ALTER COLUMN Ma_Chi_Nhanh NVARCHAR(10) NOT NULL;
ALTER TABLE CHINHANH_LIENHE ALTER COLUMN Loai_Lien_He_Email_SDT NVARCHAR(10) NOT NULL;
ALTER TABLE CHINHANH_LIENHE ALTER COLUMN Gia_Tri NVARCHAR(10) NOT NULL;

-- tbl.CHINHANH
ALTER TABLE CHINHANH ALTER COLUMN Ma_Chi_Nhanh NVARCHAR(10) NOT NULL;
ALTER TABLE CHINHANH ALTER COLUMN Ten_Chi_Nhanh NVARCHAR(100) NOT NULL;
ALTER TABLE CHINHANH ALTER COLUMN Dia_Chi NVARCHAR(200) NOT NULL;
